### ISSUE TITLE
Sound only?

### ISSUE THREAD

**Issue by mskogly** [angelnu/castv2-player#1]
When running the example code, I only get sound. 

"use strict"
let playerName     = ".."; //Change to "catstv2-player to execute outside this folder
var ScannerPromise = require(playerName).ScannerPromise();
var MediaPlayer    = require(playerName).MediaPlayer();

let mediaPlayer;
  
//Find device
return ScannerPromise(/* device name - empty-> take first device found*/)
//Create mediaPlayer
.then (function (device) {
  mediaPlayer = new MediaPlayer(device);
  return Promise.resolve();
})
//Stop player
.then (function () {
  return mediaPlayer.stopClientPromise();
})
//Start playing
.then (function () {
  return mediaPlayer.playUrlPromise("http://commondatastorage.googleapis.com/gtv-videos-bucket/CastVideos/dash/BigBuckBunnyAudio.mp4")
 })
 //Wait for the player to start playing
.then( function() {
  return new Promise(function (resolve, reject) {
    mediaPlayer.once(mediaPlayer.EVENT_PLAYER_PLAYING, function(contentId){
      console.log("PLAYING: %s", contentId);
      resolve();
      process.exit(0);
    });
  });
});

Output:
Scanner - found device Stua2 (Chromecast) at 192.168.1.71:8009
MediaPlayer - New device Stua2 at 192.168.1.71:8009
PersistentClient - Stua2 - Waiting up to 10000 seconds for connection to chromecast
PersistentClient - Stua2 - Connected client
PersistentClient - Stua2 - Connected client
PersistentPlayer - Stua2 - Try to join player
PersistentClient - Stua2 - Trying to stop client
PersistentPlayer - Stua2 - Connected player
PersistentPlayer - Stua2 - Player joint
PersistentClient - Stua2 - stopped client
PersistentPlayer - Stua2 - client disconnected
PersistentPlayer - Stua2 - Detached player
PersistentPlayer - Stua2 - Try to play url - http://commondatastorage.googleapis.com/gtv-videos-bucket/CastVideos/dash/BigBuckBunnyAudio.mp4
PersistentPlayer - Stua2 - Try to launch default player
PersistentClient - Stua2 - Waiting up to 10000 seconds for connection to chromecast
PersistentClient - Stua2 - Connected client
PersistentClient - Stua2 - Connected client
PersistentPlayer - Stua2 - Try to join player
PersistentPlayer - Stua2 - Connected player
PersistentPlayer - Stua2 - Player joint
PersistentPlayer - Stua2 - Connected player
PersistentPlayer - Stua2 - Default player lauched
PersistentPlayer - Stua2 - Try to play playlist with 1 items
PersistentPlayer - Stua2 - Started playing - http://commondatastorage.googleapis.com/gtv-videos-bucket/CastVideos/dash/BigBuckBunnyAudio.mp4
PersistentPlayer - Stua2 - Playing playlist with 1 items
PLAYING: http://commondatastorage.googleapis.com/gtv-videos-bucket/CastVideos/dash/BigBuckBunnyAudio.mp4

**Comment by angelnu** [comment]
Hi,

the examples use URLs that point to audio files. If you change that with an URL that points to video you should see video as well.

For example: http://commondatastorage.googleapis.com/gtv-videos-bucket/big_buck_bunny_1080p.mp4

**Comment by mskogly** [comment]
Ah :)
